### ISSUE TITLE
Return the private key material in the generate API

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/did-method-key-js#19]
It appears the private key material is getting dropped on the floor in the `generate` API. I expect that I would be able to get the `LDKeyPair` instance returned along with the DID document.  Is that an improper expectation?

https://github.com/digitalbazaar/did-method-key-js/blob/master/lib/driver.js#L88-L91

**Comment by dmitrizagidulin** [comment]
::facepalms:: Er, merely a dumb oversight on my part.

**Comment by dmitrizagidulin** [comment]
This does change the return signature of .generate(), so it'll be a fairly major breaking change. However, since we just changed the multicodec encoding of X25519 keys, we already have a major change to propagate downstream, so this'll be good.

**Comment by dmitrizagidulin** [comment]
@mattcollier Would it be ok to return the generated key inside the DidDocument?

The way `did-veres-one` handles it is - `generate()` returns a DID Document instance, and all the generated public/private key pairs are available at `didDoc.keys` property.

We chould change the return signature of `did:key` driver's generate to be `{keyPair, didDoc}`, but would it be ok to match the `did:v1` driver and just return `didDoc`, with the key pair being available on `didDoc.keys`?

**Comment by mattcollier** [comment]
@dmitrizagidulin having all the various methods have *some* consistent behavior would be great.  Maybe we can discuss for a few moments during today's call.

**Comment by dmitrizagidulin** [comment]
@mattcollier sure thing. (Also, for a (non-binding) example of that would look like, see https://github.com/digitalbazaar/did-method-key-js/pull/22 )

**Comment by dmitrizagidulin** [comment]
Implemented in PR #22, closing.
