### ISSUE TITLE
Support Node 12

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalbazaar/did-method-key-js#20]
Not compiling in Node 12:

```
npm i

> equihash@0.0.1-0 install ~/code/_DigitalBazaar/uni-resolver-did-v1-driver/node_modules/equihash
> node-gyp rebuild

  CXX(target) Release/obj.target/khovratovich/lib/khovratovich/addon.o
../lib/khovratovich/addon.cc:28:11: error: no member named 'Handle' in namespace 'v8'
```

**Comment by mattcollier** [comment]
@dmitrizagidulin equihash got ripped out of the did stack long ago.  I'm not sure how it's reappearing here.

**Comment by dmitrizagidulin** [comment]
@mattcollier oh huh. weird. Investigating.

**Comment by mattcollier** [comment]
@dmitrizagidulin do you have any updates on this?

**Comment by dmitrizagidulin** [comment]
@mattcollier I think this was an artifact of a stale cache or something.
I am not able to find `equihash` in the `npm ls` listing of this lib.

Closing issue.
