### ISSUE TITLE
Should id of public key contain a fragment of the key?

### ISSUE THREAD

**Issue by kdenhartog** [digitalbazaar/did-method-key-js#3]
I noticed that the dh key uses a fragment in the identifier, but the ed25519 key doesn't use the identifier. Is this intentional @dmitrizagidulin ? 

https://github.com/digitalbazaar/did-method-key-js/blob/a224aec5097c9f083a91982a752b9e3a0d453e4f/lib/driver.js#L58

**Comment by dmitrizagidulin** [comment]
@kdenhartog - ::facepalms:: no, not intentional, need to fix that. :)
Thanks for the catch!

**Comment by dmitrizagidulin** [comment]
Should be addressed by #4.

**Comment by dmitrizagidulin** [comment]
Fixed in PR #4, closing. Thanks again! :)
