### ISSUE TITLE
Slated changes for v1.0.0 release

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/did-method-key-js#31]
- Update lib to use [cryptold@4](https://github.com/digitalbazaar/crypto-ld/blob/master/CHANGELOG.md#402---2020-08-01) which has simplified dependencies.
- Possibly change the name of the repo to `did-method-key`
- scope the 1.0.0 package under `@digitalbazaar`

Others?

**Comment by dmitrizagidulin** [comment]
Closing, implemented. (Renaming repo will have to be done as a separate item.)
